#
# Homebrew Bundle
# See: https://github.com/Homebrew/homebrew-bundle
#

#
# 'brew tap'
#

tap "homebrew/bundle"
tap "homebrew/cask"

#
# 'brew install'
#

brew "coreutils"
brew "curl"
brew "git"
brew "gnupg"
brew "mas"
brew "nano"
brew "node"
brew "jq"
brew "tmux"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"

#
# 'brew install --cask'
#

cask "adobe-creative-cloud"
cask "discord"
cask "figma"
cask "google-chrome"
cask "tunnelbear"
cask "visual-studio-code"

#
# 'mas install'
#

mas "AdGuard for Safari", id: 1440147259
mas "Data Jar", id: 1453273600
mas "Grammarly for Safari", id: 1462114288
mas "Magnet", id: 441258766
mas "The Unarchiver", id: 425424353
#mas "Xcode", id: 497799835
