#
# System-wide profile for interactive zsh(1) shells.
#

# Setup user specific overrides for this in ~/.zprofile.
# See zshbuiltins(1) and zshoptions(1) for more details.
if [[ -n "$PS1" ]]; then
  source "${ZDOTDIR}/.zshrc"
fi
