#!/bin/zsh

# Environment variables for launchd.
# Ref: https://support.apple.com/en-gb/guide/terminal/apdc6c1077b-5d5d-4d35-9c19-60f2397b2369/mac

launch() {
  local COMMAND="${1}"
  local AGENT="${2}"
  local LIB_AGENTS="${HOME}/Library/LaunchAgents"

  # Show `help` message.
  if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    echo "Usage: launch [OPTION] [FILE]"
    echo
    echo "Options:"
    echo "  -d, --dir       Navigate to the user's agents directory"
    echo "  -l, --list      List all running launchctl daemons/agents"
    echo "  -g, --grep      Filter the list of launchctl daemons/agents"
    echo
    echo "  -L, --load      Load the specified configuration file"
    echo "  -R, --reload    Reload the specified configuration file"
    echo "  -S, --start     Start the specified job by label"
    echo
    echo "  -u, --unload    Unload the specified configuration file"
    echo "  -r, --remove    Remove the job from launchd by label"
    echo "  -s, --stop      Stop the specified job by label"
    echo
    echo "  -h, --help      Display this help and exit"
    echo
    echo "For more information, see 'man launchd' and 'man launchctl'."
    return 0
  fi

  # Launchd Services
  if [[ "$COMMAND" == "-d" || "$COMMAND" == "--dir" ]]; then
    cd "${LIB_AGENTS}" || return
  elif [[ "$COMMAND" == "-l" || "$COMMAND" == "--list" ]]; then
    launchctl list
  elif [[ "$COMMAND" == "-g" || "$COMMAND" == "--grep" && -n "$AGENT" ]]; then
    launchctl list | grep "${AGENT}"
  elif [[ "$COMMAND" == "-R" || "$COMMAND" == "--reload" && -n "$AGENT" ]]; then
    pushd "${LIB_AGENTS}" > /dev/null && echo "reloading ${AGENT}" && launchctl unload "${AGENT}" && launchctl load "${AGENT}" && popd > /dev/null
  elif [[ "$COMMAND" == "-L" || "$COMMAND" == "--load" && -n "$AGENT" ]]; then
    pushd "${LIB_AGENTS}" > /dev/null && echo "loading ${AGENT}" && launchctl load "${AGENT}" && popd > /dev/null
  elif [[ "$COMMAND" == "-u" || "$COMMAND" == "--unload" && -n "$AGENT" ]]; then
    pushd "${LIB_AGENTS}" > /dev/null && echo "unloading ${AGENT}" && launchctl unload "${AGENT}" && popd > /dev/null
  elif [[ "$COMMAND" == "-S" || "$COMMAND" == "--start" && -n "$AGENT" ]]; then
    pushd "${LIB_AGENTS}" > /dev/null && echo "starting ${AGENT}" && launchctl start "${AGENT}" && popd > /dev/null
  elif [[ "$COMMAND" == "-s" || "$COMMAND" == "--stop" && -n "$AGENT" ]]; then
    pushd "${LIB_AGENTS}" > /dev/null && echo "stopping ${AGENT}" && launchctl stop "${AGENT}" && popd > /dev/null
  elif [[ "$COMMAND" == "-r" || "$COMMAND" == "--remove" && -n "$AGENT" ]]; then
    pushd "${LIB_AGENTS}" > /dev/null && echo "removing ${AGENT}" && launchctl remove "${AGENT}" && popd > /dev/null
  else
    echo "launch: command not found or plist file is not defined"
    return 1
  fi
}
